/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanly_hoso;

import java.awt.Component;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Long
 */
public class frm_HOSO extends javax.swing.JFrame {

    private DSHS dsHoSo;
    private DefaultTableModel dtmHoSo;

    /**
     * Creates new form frm_HOSO
     */
    public frm_HOSO() {
        initComponents();
        myInit();
    }

    private void myInit() {
        dtmHoSo = (DefaultTableModel) tbHoSo.getModel();
        tbHoSo.setModel(dtmHoSo);
        dsHoSo = new DSHS();
    }

    private void XoaDuLieu() {
        while (dtmHoSo.getRowCount() > 0) {
            dtmHoSo.removeRow(0);
        }
    }
    
    private String NgheNghiep(HOSO hs){
        if(hs instanceof HOCSINH){
            return "Học sinh";
        }else {
            return "Giáo viên";
        }
    }
    private void ThemMotDong(HOSO hs) {
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        dtmHoSo.addRow(new Object[]{
            hs.getMaHoSo(), hs.getHoTen(), hs.getSoCMND(), df.format(hs.getNgaySinh()), NgheNghiep(hs)
        });
    }

    private void NapDuLieu() {
        XoaDuLieu();
        for (HOSO hs : dsHoSo.getDs()) {
            ThemMotDong(hs);
        }
    }

    void setPanelEnabled(JPanel panel, Boolean isEnabled) {
        panel.setEnabled(isEnabled);

        Component[] components = panel.getComponents();

        for (Component component : components) {
            if (component instanceof JPanel) {
                setPanelEnabled((JPanel) component, isEnabled);
            }
            component.setEnabled(isEnabled);
        }
    }

    private void setValuesNull() {
        setGiaoVienNull();
        setHocSinhNul();
        txtCMND.setText("");
        txtMaHS.setText("");
        txtNgaySinh.setText("");
        txtHoTen.setText("");
        txtMaHS.requestFocus();
        txtSoLuongGV.setText("");
        txtSoLuongHS.setText("");
    }

    private void setHocSinhNul() {
        txtDiemHoa.setText("");
        txtDiemLy.setText("");
        txtDiemToan.setText("");
        txtHocBong.setText("");
        txtMaHocSinh.setText("");
        txtXepLoai.setText("");
        txtDiemTB.setText("");
    }

    private void setGiaoVienNull() {
        txtDanhGiaXL.setText("");
        txtDiemThiDua.setText("");
        txtHSL.setText("");
        txtLuong.setText("");
        txtMaGV.setText("");
        txtNgayVao.setText("");
        txtPhuCap.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaHS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cbGiaoVien = new javax.swing.JRadioButton();
        cbHocSinh = new javax.swing.JRadioButton();
        pnGiaoVien = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaGV = new javax.swing.JTextField();
        txtNgayVao = new javax.swing.JTextField();
        txtDiemThiDua = new javax.swing.JTextField();
        txtHSL = new javax.swing.JTextField();
        pnHocSinh = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMaHocSinh = new javax.swing.JTextField();
        txtDiemToan = new javax.swing.JTextField();
        txtDiemLy = new javax.swing.JTextField();
        txtDiemHoa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHoSo = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnDatLai = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtSoLuongHS = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtSoLuongGV = new javax.swing.JTextField();
        pnGV = new javax.swing.JPanel();
        txtDanhGiaXL = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtLuong = new javax.swing.JTextField();
        txtPhuCap = new javax.swing.JTextField();
        pnHs = new javax.swing.JPanel();
        pnHS = new javax.swing.JLabel();
        txtDiemTB = new javax.swing.JTextField();
        txtXepLoai = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtHocBong = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel7.setText("jLabel7");

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("form: QUẢN LÝ HỒ SƠ");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("QUẢN LÝ HỒ SƠ");

        jLabel2.setForeground(new java.awt.Color(166, 59, 48));
        jLabel2.setText("MÃ HỒ SƠ");

        jLabel3.setForeground(new java.awt.Color(166, 59, 48));
        jLabel3.setText("HỌ TÊN");

        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(166, 59, 48));
        jLabel4.setText("SỐ CMND");

        jLabel5.setForeground(new java.awt.Color(166, 59, 48));
        jLabel5.setText("NGÀY SINH");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nghề nghiệp", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        buttonGroup1.add(cbGiaoVien);
        cbGiaoVien.setText("GIÁO VIÊN");
        cbGiaoVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGiaoVienActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbHocSinh);
        cbHocSinh.setText("HỌC SINH");
        cbHocSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHocSinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbHocSinh)
                    .addComponent(cbGiaoVien))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbGiaoVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbHocSinh)
                .addContainerGap())
        );

        pnGiaoVien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GIÁO VIÊN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        pnGiaoVien.setForeground(new java.awt.Color(0, 51, 255));

        jLabel6.setForeground(new java.awt.Color(166, 59, 48));
        jLabel6.setText("MÃ GIÁO VIÊN");

        jLabel8.setForeground(new java.awt.Color(166, 59, 48));
        jLabel8.setText("NGÀY VÀO");

        jLabel9.setForeground(new java.awt.Color(166, 59, 48));
        jLabel9.setText("ĐIỂM THI ĐUA");

        jLabel10.setForeground(new java.awt.Color(166, 59, 48));
        jLabel10.setText("HỆ SỐ LƯƠNG");

        txtDiemThiDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemThiDuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnGiaoVienLayout = new javax.swing.GroupLayout(pnGiaoVien);
        pnGiaoVien.setLayout(pnGiaoVienLayout);
        pnGiaoVienLayout.setHorizontalGroup(
            pnGiaoVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGiaoVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnGiaoVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(pnGiaoVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaGV, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(txtNgayVao)
                    .addComponent(txtDiemThiDua)
                    .addComponent(txtHSL))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnGiaoVienLayout.setVerticalGroup(
            pnGiaoVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGiaoVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnGiaoVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnGiaoVienLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtMaGV)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnGiaoVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayVao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnGiaoVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemThiDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnGiaoVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnHocSinh.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HỌC SINH", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        pnHocSinh.setForeground(new java.awt.Color(0, 51, 255));

        jLabel11.setForeground(new java.awt.Color(166, 59, 48));
        jLabel11.setText("MÃ HỌC SINH");

        jLabel12.setForeground(new java.awt.Color(166, 59, 48));
        jLabel12.setText("ĐIỂM TOÁN");

        jLabel13.setForeground(new java.awt.Color(166, 59, 48));
        jLabel13.setText("ĐIỂM LÝ");

        jLabel14.setForeground(new java.awt.Color(166, 59, 48));
        jLabel14.setText("ĐIỂM HÓA");

        txtDiemToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnHocSinhLayout = new javax.swing.GroupLayout(pnHocSinh);
        pnHocSinh.setLayout(pnHocSinhLayout);
        pnHocSinhLayout.setHorizontalGroup(
            pnHocSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHocSinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnHocSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(pnHocSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaHocSinh, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(txtDiemToan)
                    .addComponent(txtDiemLy)
                    .addComponent(txtDiemHoa))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pnHocSinhLayout.setVerticalGroup(
            pnHocSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHocSinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnHocSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaHocSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnHocSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiemToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnHocSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiemLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnHocSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tbHoSo.setForeground(new java.awt.Color(51, 0, 255));
        tbHoSo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hồ sơ", "Họ tên", "Số CMND", "Ngày sinh", "Nghề nghiệp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbHoSo.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tbHoSo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHoSoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHoSo);

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCapNhat.setText("CẬP NHẬT");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTimKiem.setText("TÌM KIẾM");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnThongKe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThongKe.setText("THỐNG KÊ");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnDatLai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDatLai.setText("ĐẶT LẠI");
        btnDatLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLaiActionPerformed(evt);
            }
        });

        jLabel20.setForeground(new java.awt.Color(166, 59, 48));
        jLabel20.setText("SỐ LƯỢNG HỌC SINH");

        jLabel21.setForeground(new java.awt.Color(166, 59, 48));
        jLabel21.setText("SỐ LƯỢNG GIÁO VIÊN");

        pnGV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 11))); // NOI18N
        pnGV.setForeground(new java.awt.Color(0, 51, 255));

        jLabel15.setForeground(new java.awt.Color(166, 59, 48));
        jLabel15.setText("ĐÁNH GIÁ XL");

        jLabel16.setForeground(new java.awt.Color(166, 59, 48));
        jLabel16.setText("PHỤ CẤP");

        jLabel17.setForeground(new java.awt.Color(166, 59, 48));
        jLabel17.setText("LƯƠNG");

        txtLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnGVLayout = new javax.swing.GroupLayout(pnGV);
        pnGV.setLayout(pnGVLayout);
        pnGVLayout.setHorizontalGroup(
            pnGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(pnGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDanhGiaXL)
                    .addComponent(txtPhuCap)
                    .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnGVLayout.setVerticalGroup(
            pnGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnGVLayout.createSequentialGroup()
                .addGroup(pnGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDanhGiaXL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnGVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnHs.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 11))); // NOI18N
        pnHs.setForeground(new java.awt.Color(0, 51, 255));

        pnHS.setForeground(new java.awt.Color(166, 59, 48));
        pnHS.setText("ĐIỂM TB");

        txtDiemTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemTBActionPerformed(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(166, 59, 48));
        jLabel18.setText("XẾP LOẠI");

        jLabel19.setForeground(new java.awt.Color(166, 59, 48));
        jLabel19.setText("HỌC BỔNG");

        txtHocBong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHocBongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnHsLayout = new javax.swing.GroupLayout(pnHs);
        pnHs.setLayout(pnHsLayout);
        pnHsLayout.setHorizontalGroup(
            pnHsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnHsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnHS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(pnHsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtXepLoai)
                    .addComponent(txtHocBong)
                    .addComponent(txtDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnHsLayout.setVerticalGroup(
            pnHsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHsLayout.createSequentialGroup()
                .addGroup(pnHsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnHS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnHsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtXepLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnHsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHocBong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnGiaoVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnHocSinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnHs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem)
                            .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(btnCapNhat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnXoa)
                            .addComponent(txtSoLuongHS, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTimKiem)
                                .addGap(67, 67, 67)
                                .addComponent(btnDatLai))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSoLuongGV, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaHS, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(268, 268, 268))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMaHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnGiaoVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnHocSinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnHs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongKe)
                    .addComponent(txtSoLuongGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuongHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa)
                    .addComponent(btnTimKiem)
                    .addComponent(btnDatLai))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void cbGiaoVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGiaoVienActionPerformed
        // TODO add your handling code here:
        setPanelEnabled(pnGiaoVien, true);
        setPanelEnabled(pnHocSinh, false);
        setPanelEnabled(pnGV, true);
        setPanelEnabled(pnHs, false);
        txtDanhGiaXL.setEditable(false);
        txtPhuCap.setEditable(false);
        txtLuong.setEditable(false);
    }//GEN-LAST:event_cbGiaoVienActionPerformed

    private void cbHocSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHocSinhActionPerformed
        // TODO add your handling code here:
        setPanelEnabled(pnGiaoVien, false);
        setPanelEnabled(pnHocSinh, true);
        setPanelEnabled(pnGV, false);
        setPanelEnabled(pnHs, true);
        txtHocBong.setEditable(false);
        txtXepLoai.setEditable(false);
        txtDiemTB.setEditable(false);
    }//GEN-LAST:event_cbHocSinhActionPerformed

    private void txtDiemThiDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemThiDuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemThiDuaActionPerformed

    private void txtDiemToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemToanActionPerformed

    private void txtLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuongActionPerformed

    private void txtHocBongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHocBongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHocBongActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.dsHoSo.Xoa(txtMaHS.getText());
        setValuesNull();
        NapDuLieu();
        txtMaHS.requestFocus();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        Date ngaySinh = new Date();
        Date ngayVao = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        try {
            ngaySinh = df.parse(txtNgaySinh.getText());
        } catch (ParseException ex) {
            Logger.getLogger(frm_HOSO.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ngayVao = df.parse(txtNgayVao.getText());
        } catch (ParseException ex) {
            Logger.getLogger(frm_HOSO.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (cbHocSinh.isSelected()) {
            setGiaoVienNull();
            HOSO hs = new HOCSINH(txtMaHocSinh.getText(), Double.parseDouble(txtDiemToan.getText()), Double.parseDouble(txtDiemLy.getText()), Double.parseDouble(txtDiemHoa.getText()), txtMaHS.getText(), txtHoTen.getText(), Long.parseLong(txtCMND.getText()), ngaySinh);
            dsHoSo.Them(hs);
            NapDuLieu();
        }
        if (cbGiaoVien.isSelected()) {
            setHocSinhNul();
            HOSO gv = new GIAOVIEN(txtMaGV.getText(), ngayVao, Double.parseDouble(txtDiemThiDua.getText()), Double.parseDouble(txtHSL.getText()), txtMaHS.getText(), txtHoTen.getText(), Long.parseLong(txtCMND.getText()), ngaySinh);
            dsHoSo.Them(gv);
            NapDuLieu();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnDatLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLaiActionPerformed
        // TODO add your handling code here:
        txtMaHS.requestFocus();
        setValuesNull();
        setPanelEnabled(pnGV, true);
        setPanelEnabled(pnHs, true);
        setPanelEnabled(pnHocSinh, true);
        setPanelEnabled(pnGiaoVien, true);
        cbGiaoVien.setSelected(false);
        cbHocSinh.setSelected(false);
    }//GEN-LAST:event_btnDatLaiActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        txtDanhGiaXL.setText("");
        txtPhuCap.setText("");
        txtLuong.setText("");
        txtDiemTB.setText("");
        txtXepLoai.setText("");
        txtHocBong.setText("");
        txtMaHS.requestFocus();
        Date ngaySinh = new Date();
        Date ngayVao = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        try {
            ngaySinh = df.parse(txtNgaySinh.getText());
        } catch (ParseException ex) {
            Logger.getLogger(frm_HOSO.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ngayVao = df.parse(txtNgayVao.getText());
        } catch (ParseException ex) {
            Logger.getLogger(frm_HOSO.class.getName()).log(Level.SEVERE, null, ex);
        }
        HOSO hs;
        if (cbHocSinh.isSelected()) {
            setGiaoVienNull();
            hs = new HOCSINH(txtMaHocSinh.getText(), Double.parseDouble(txtDiemToan.getText()), Double.parseDouble(txtDiemLy.getText()), Double.parseDouble(txtDiemHoa.getText()), txtMaHS.getText(), txtHoTen.getText(), Long.parseLong(txtCMND.getText()), ngaySinh);
            this.dsHoSo.CapNhap(hs);
            NapDuLieu();
        }
        if (cbGiaoVien.isSelected()) {
            setHocSinhNul();
            hs = new GIAOVIEN(txtMaGV.getText(), ngayVao, Double.parseDouble(txtDiemThiDua.getText()), Double.parseDouble(txtHSL.getText()), txtMaHS.getText(), txtHoTen.getText(), Long.parseLong(txtCMND.getText()), ngaySinh);
            this.dsHoSo.CapNhap(hs);
            NapDuLieu();
        }

    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        txtMaHS.requestFocus();
        HOSO hs = dsHoSo.Tim(txtMaHS.getText());
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        NumberFormat nf = NumberFormat.getInstance(Locale.ENGLISH);
        txtMaHS.setText(hs.getMaHoSo());
        txtCMND.setText(String.valueOf(hs.getSoCMND()));
        txtHoTen.setText(hs.getHoTen());
        txtNgaySinh.setText(df.format(hs.getNgaySinh()));
        if (hs instanceof GIAOVIEN) {
            GIAOVIEN gv = (GIAOVIEN) hs;
            cbGiaoVien.setSelected(true);
            cbHocSinh.setSelected(false);
            setPanelEnabled(pnGV, true);
            setPanelEnabled(pnHs, false);
            setPanelEnabled(pnGiaoVien, true);
            setPanelEnabled(pnHocSinh, false);
            setHocSinhNul();
            txtMaGV.setText(gv.getMaGV());
            txtDanhGiaXL.setText(gv.DanhGiaXepLoai());
            txtNgayVao.setText(df.format(gv.getNgayVao()));
            txtDiemThiDua.setText(nf.format(gv.getDiemThiDua()));
            txtHSL.setText(nf.format(gv.getHSL()));
            txtPhuCap.setText(nf.format(gv.PhuCap()));
            txtLuong.setText(nf.format(gv.Luong()));
        } else {
            HOCSINH hsi = (HOCSINH) hs;
            cbHocSinh.setSelected(true);
            cbGiaoVien.setSelected(false);
            setPanelEnabled(pnGV, false);
            setPanelEnabled(pnHs, true);
            setPanelEnabled(pnGiaoVien, false);
            setPanelEnabled(pnHocSinh, true);
            setGiaoVienNull();
            txtDiemHoa.setText(nf.format(hsi.getDiemHoa()));
            txtDiemToan.setText(nf.format(hsi.getDiemToan()));
            txtDiemLy.setText(nf.format(hsi.getDiemLy()));
            txtMaHocSinh.setText(hsi.getMaHS());
            txtDiemTB.setText(nf.format(hsi.DTB()));
            txtXepLoai.setText(hsi.DanhGiaXepLoai());
            txtHocBong.setText(nf.format(hsi.TinhHocBong()));
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tbHoSoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHoSoMouseClicked
        // TODO add your handling code here:
        int row = tbHoSo.rowAtPoint(evt.getPoint());
        HOSO hs = dsHoSo.Tim(String.valueOf(tbHoSo.getValueAt(row, 0)).trim());
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        NumberFormat nf = NumberFormat.getInstance(Locale.ENGLISH);
        txtMaHS.setText(hs.getMaHoSo());
        txtCMND.setText(String.valueOf(hs.getSoCMND()));
        txtHoTen.setText(hs.getHoTen());
        txtNgaySinh.setText(df.format(hs.getNgaySinh()));
        if (hs instanceof GIAOVIEN) {
            GIAOVIEN gv = (GIAOVIEN) hs;
            cbGiaoVien.setSelected(true);
            cbHocSinh.setSelected(false);
            setPanelEnabled(pnGiaoVien, true);
            setPanelEnabled(pnHocSinh, false);
            setPanelEnabled(pnGV, true);
            setPanelEnabled(pnHs, false);
            txtMaGV.setText(gv.getMaGV());
            txtDanhGiaXL.setText(gv.DanhGiaXepLoai());
            txtNgayVao.setText(df.format(gv.getNgayVao()));
            txtDiemThiDua.setText(nf.format(gv.getDiemThiDua()));
            txtHSL.setText(nf.format(gv.getHSL()));
            txtPhuCap.setText(nf.format(gv.PhuCap()));
            txtLuong.setText(nf.format(gv.Luong()));
        }
        if (hs instanceof HOCSINH) {
            HOCSINH hsi = (HOCSINH) hs;
            cbHocSinh.setSelected(true);
            cbGiaoVien.setSelected(false);
            setPanelEnabled(pnGiaoVien, false);
            setPanelEnabled(pnHocSinh, true);
            setPanelEnabled(pnGV, false);
            setPanelEnabled(pnHs, true);
            txtDiemHoa.setText(nf.format(hsi.getDiemHoa()));
            txtDiemToan.setText(nf.format(hsi.getDiemToan()));
            txtDiemLy.setText(nf.format(hsi.getDiemLy()));
            txtMaHocSinh.setText(hsi.getMaHS());
            txtDiemTB.setText(nf.format(hsi.DTB()));
            txtXepLoai.setText(hsi.DanhGiaXepLoai());
            txtHocBong.setText(nf.format(hsi.TinhHocBong()));
        }
    }//GEN-LAST:event_tbHoSoMouseClicked

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:      
        txtSoLuongGV.setText(String.valueOf(this.dsHoSo.ThongKeGV()));
        txtSoLuongHS.setText(String.valueOf(this.dsHoSo.ThongKeHS()));
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void txtDiemTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemTBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_HOSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_HOSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_HOSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_HOSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_HOSO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDatLai;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cbGiaoVien;
    private javax.swing.JRadioButton cbHocSinh;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnGV;
    private javax.swing.JPanel pnGiaoVien;
    private javax.swing.JLabel pnHS;
    private javax.swing.JPanel pnHocSinh;
    private javax.swing.JPanel pnHs;
    private javax.swing.JTable tbHoSo;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDanhGiaXL;
    private javax.swing.JTextField txtDiemHoa;
    private javax.swing.JTextField txtDiemLy;
    private javax.swing.JTextField txtDiemTB;
    private javax.swing.JTextField txtDiemThiDua;
    private javax.swing.JTextField txtDiemToan;
    private javax.swing.JTextField txtHSL;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtHocBong;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMaGV;
    private javax.swing.JTextField txtMaHS;
    private javax.swing.JTextField txtMaHocSinh;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtNgayVao;
    private javax.swing.JTextField txtPhuCap;
    private javax.swing.JTextField txtSoLuongGV;
    private javax.swing.JTextField txtSoLuongHS;
    private javax.swing.JTextField txtXepLoai;
    // End of variables declaration//GEN-END:variables
}
